### ISSUE TITLE
Documentation is broken for AppShell component

### ISSUE THREAD

**Issue by ihavenonickname** [Secullum/secullum-react-native-ui#96]
Steps to repro:

1. Go to https://secullum.github.io/secullum-react-native-ui/
2. Expand the "Components" section
3. Click AppShell (first component in the list)

You get an error message and a stack trace.

```
🚨 Whoops, we crashed 🚨
t is not a function
Stack trace

in HeaderDesktop
in DimensionsMonitor
in AppShell
in Ut
in div
in Styled(div)
in div
...
```

**Comment by fhelwanger** [comment]
Fixed in d520d4bc963a6cddbb44fa0eb7cfdfed8efdf765
